### ISSUE TITLE
JSON order is not maintained

### ISSUE THREAD

**Issue by mbfattep** [mseclab/PyJFuzz#6] opened 2018-02-14 05:19 UTC
I have provided a sample JSON file with below content and the fuzzed JSON file order is not same as original.

Original: {        "data": "Click Here", "vOffset": 100,        "alignment": "center"    }
Fuzzed: {"vOffset": true, "data": false, "alignment": {"param": "${7*7}a{{cente}}b"}}

Details:
Execution command: C:\Python27\Scripts\pjf.exe --F <filename.json>

I have executed more than 20 times and order is maintained in any run.

**Comment by dzonerzy** [comment] 2018-02-14 10:37
Please note according to JSON rfc an object is an **unordered dictionary** so i'm closing this since it's not a bug.

**Closed by dzonerzy** 2018-02-14 10:37 UTC
